AWSTemplateFormatVersion: 2010-09-09
Descriptions: First CFN Template

Resources:
  MyFirstEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: 
      KeyName: 
      SecurityGroup:
        - default