AWSTemplateFormatVersion: 2010-09-09
Description: Add EIP to the EC2 Instance
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-02f9ea74050d6f812
      KeyName: Public-Testing-eu-central-1
      SecurityGroups:
        - default
        - !Ref MySG
  
  MySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and Http
      GroupName: SSH-HTTP
      Tags:
        - Key: Name
          Value: SSH-HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH from Corporate office
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: Port for Apache Server
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyEC2Instance
      Tags:
        - Key: Name
          Value: MyPersonalEIP

  
