AWSTemplateFormatVersion: 2010-09-09
Description: Second Template with Security Group
Resources:
  secondcfm:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02f9ea74050d6f812
      InstanceType: t2.micro
      KeyName: Public-Testing-eu-central-1
      SecurityGroups:
        - default
        - !Ref sshsg

  sshsg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from anywhere
      GroupName: SSHWorld
      SecurityGroupIngress:
        - FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp


